enum AppLanguage {
  de('de', 'Deutsch', '🇩🇪', false),
  en('en', 'English', '🇬🇧', false),
  tr('tr', 'Türkçe', '🇹🇷', false),
  ar('ar', 'العربية', '🇸🇦', true),
  uk('uk', 'Українська', '🇺🇦', false);

  const AppLanguage(this.code, this.label, this.flag, this.isRtl);

  final String code;
  final String label;
  final String flag;
  final bool isRtl;

  static AppLanguage fromCode(String? code) => AppLanguage.values.firstWhere(
    (language) => language.code == code,
    orElse: () => AppLanguage.de,
  );
}

enum AppText {
  allAreas,
  open,
  scanDocument,
  dailyPlan,
  anamnesis,
  anamnesisSubtitle,
  anamnesisDesc,
  healthcare,
  healthcareSubtitle,
  healthcareDesc,
  treatmentHistory,
  treatmentHistorySubtitle,
  treatmentHistoryDesc,
  vaccination,
  vaccinationSubtitle,
  vaccinationDesc,
  medication,
  medicationSubtitle,
  medicationDesc,
  appointments,
  appointmentsSubtitle,
  appointmentsDesc,
  allergies,
  allergiesSubtitle,
  allergiesDesc,
  prevention,
  preventionSubtitle,
  preventionDesc,
  bloodPressure,
  bloodPressureSubtitle,
  bloodPressureDesc,
  weight,
  weightSubtitle,
  weightDesc,
  healthExport,
  familyCircle,
  interactionCheck,
}

extension AppLanguageText on AppLanguage {
  String t(AppText key) =>
      _translations[this]?[key] ?? _translations[AppLanguage.de]![key]!;
}

const _translations = {
  AppLanguage.de: {
    AppText.allAreas: 'ALLE BEREICHE',
    AppText.open: 'Öffnen',
    AppText.scanDocument: 'Dokument scannen',
    AppText.dailyPlan: 'Tagesplan',
    AppText.anamnesis: 'Anamnese',
    AppText.anamnesisSubtitle: 'Krankengeschichte',
    AppText.anamnesisDesc: 'Ihre medizinische Vorgeschichte',
    AppText.healthcare: 'Heilberufe',
    AppText.healthcareSubtitle: 'Ärzte & Behandler',
    AppText.healthcareDesc: 'Alle Ihre Ärzte und Therapeuten',
    AppText.treatmentHistory: 'Behandlungshistorie',
    AppText.treatmentHistorySubtitle: 'Behandlungsübersicht',
    AppText.treatmentHistoryDesc: 'Alle Behandlungen im Überblick',
    AppText.vaccination: 'Impfpass',
    AppText.vaccinationSubtitle: 'Impfungen & Pässe',
    AppText.vaccinationDesc: 'Impfungen und Gesundheitspässe',
    AppText.medication: 'Medikation',
    AppText.medicationSubtitle: 'Medikamentenplan',
    AppText.medicationDesc: 'Ihre aktuellen Medikamente',
    AppText.appointments: 'Termine',
    AppText.appointmentsSubtitle: 'Arzttermine',
    AppText.appointmentsDesc: 'Alle anstehenden Termine',
    AppText.allergies: 'Allergien',
    AppText.allergiesSubtitle: 'Unverträglichkeiten',
    AppText.allergiesDesc: 'Ihre Allergien und Unverträglichkeiten',
    AppText.prevention: 'Vorsorge',
    AppText.preventionSubtitle: 'Prävention',
    AppText.preventionDesc: 'Vorsorgeuntersuchungen',
    AppText.bloodPressure: 'Blutdruck',
    AppText.bloodPressureSubtitle: 'Messwerte',
    AppText.bloodPressureDesc: 'Blutdruck und Puls',
    AppText.weight: 'Gewicht',
    AppText.weightSubtitle: 'BMI & Verlauf',
    AppText.weightDesc: 'Gewichtskontrolle',
    AppText.healthExport: 'Gesundheitsakte exportieren',
    AppText.familyCircle: 'Familienkreis',
    AppText.interactionCheck: 'Wechselwirkungen',
  },
  AppLanguage.en: {
    AppText.allAreas: 'ALL AREAS',
    AppText.open: 'Open',
    AppText.scanDocument: 'Scan Document',
    AppText.dailyPlan: 'Daily Plan',
    AppText.anamnesis: 'Medical History',
    AppText.anamnesisSubtitle: 'Health History',
    AppText.anamnesisDesc: 'Your medical background',
    AppText.healthcare: 'Healthcare Professionals',
    AppText.healthcareSubtitle: 'Doctors & Therapists',
    AppText.healthcareDesc: 'All your doctors and therapists',
    AppText.treatmentHistory: 'Treatment History',
    AppText.treatmentHistorySubtitle: 'Treatment Overview',
    AppText.treatmentHistoryDesc: 'All treatments at a glance',
    AppText.vaccination: 'Vaccination Record',
    AppText.vaccinationSubtitle: 'Vaccinations & Passes',
    AppText.vaccinationDesc: 'Vaccinations and health passes',
    AppText.medication: 'Medication',
    AppText.medicationSubtitle: 'Medication Plan',
    AppText.medicationDesc: 'Your current medications',
    AppText.appointments: 'Appointments',
    AppText.appointmentsSubtitle: 'Medical Appointments',
    AppText.appointmentsDesc: 'All upcoming appointments',
    AppText.allergies: 'Allergies',
    AppText.allergiesSubtitle: 'Intolerances',
    AppText.allergiesDesc: 'Your allergies and intolerances',
    AppText.prevention: 'Prevention',
    AppText.preventionSubtitle: 'Preventive Care',
    AppText.preventionDesc: 'Preventive examinations',
    AppText.bloodPressure: 'Blood Pressure',
    AppText.bloodPressureSubtitle: 'Readings',
    AppText.bloodPressureDesc: 'Blood pressure and pulse',
    AppText.weight: 'Weight',
    AppText.weightSubtitle: 'BMI & Trend',
    AppText.weightDesc: 'Weight tracking',
    AppText.healthExport: 'Export health record',
    AppText.familyCircle: 'Family Circle',
    AppText.interactionCheck: 'Interactions',
  },
  AppLanguage.tr: {
    AppText.allAreas: 'TÜM ALANLAR',
    AppText.open: 'Aç',
    AppText.scanDocument: 'Belge Tara',
    AppText.dailyPlan: 'Günlük Plan',
    AppText.anamnesis: 'Anamnez',
    AppText.anamnesisSubtitle: 'Hastalık Geçmişi',
    AppText.anamnesisDesc: 'Tıbbi geçmişiniz',
    AppText.healthcare: 'Sağlık Personeli',
    AppText.healthcareSubtitle: 'Doktorlar ve Terapistler',
    AppText.healthcareDesc: 'Tüm doktorlarınız ve terapistleriniz',
    AppText.treatmentHistory: 'Tedavi Geçmişi',
    AppText.treatmentHistorySubtitle: 'Tedavi Özeti',
    AppText.treatmentHistoryDesc: 'Tüm tedavilere genel bakış',
    AppText.vaccination: 'Aşı Kartı',
    AppText.vaccinationSubtitle: 'Aşılar ve Pasaportlar',
    AppText.vaccinationDesc: 'Aşılar ve sağlık pasaportları',
    AppText.medication: 'İlaç',
    AppText.medicationSubtitle: 'İlaç Planı',
    AppText.medicationDesc: 'Mevcut ilaçlarınız',
    AppText.appointments: 'Randevular',
    AppText.appointmentsSubtitle: 'Doktor Randevuları',
    AppText.appointmentsDesc: 'Yaklaşan tüm randevular',
    AppText.allergies: 'Alerjiler',
    AppText.allergiesSubtitle: 'İntoleranslar',
    AppText.allergiesDesc: 'Alerjileriniz ve intoleranslarınız',
    AppText.prevention: 'Önleme',
    AppText.preventionSubtitle: 'Koruyucu Bakım',
    AppText.preventionDesc: 'Önleyici muayeneler',
    AppText.bloodPressure: 'Tansiyon',
    AppText.bloodPressureSubtitle: 'Ölçümler',
    AppText.bloodPressureDesc: 'Tansiyon ve nabız',
    AppText.weight: 'Kilo',
    AppText.weightSubtitle: 'BMI ve Gidişat',
    AppText.weightDesc: 'Kilo takibi',
    AppText.healthExport: 'Sağlık kaydını dışa aktar',
    AppText.familyCircle: 'Aile çevresi',
    AppText.interactionCheck: 'Etkileşimler',
  },
  AppLanguage.ar: {
    AppText.allAreas: 'جميع المجالات',
    AppText.open: 'فتح',
    AppText.scanDocument: 'مسح المستند',
    AppText.dailyPlan: 'الخطة اليومية',
    AppText.anamnesis: 'التاريخ المرضي',
    AppText.anamnesisSubtitle: 'التاريخ الصحي',
    AppText.anamnesisDesc: 'خلفيتك الطبية',
    AppText.healthcare: 'المهنيون الصحيون',
    AppText.healthcareSubtitle: 'الأطباء والمعالجون',
    AppText.healthcareDesc: 'جميع أطبائك ومعالجيك',
    AppText.treatmentHistory: 'تاريخ العلاج',
    AppText.treatmentHistorySubtitle: 'نظرة عامة على العلاج',
    AppText.treatmentHistoryDesc: 'جميع العلاجات في لمحة',
    AppText.vaccination: 'سجل التطعيم',
    AppText.vaccinationSubtitle: 'التطعيمات والجوازات',
    AppText.vaccinationDesc: 'التطعيمات وجوازات الصحة',
    AppText.medication: 'الأدوية',
    AppText.medicationSubtitle: 'خطة الدواء',
    AppText.medicationDesc: 'أدويتك الحالية',
    AppText.appointments: 'المواعيد',
    AppText.appointmentsSubtitle: 'المواعيد الطبية',
    AppText.appointmentsDesc: 'جميع المواعيد القادمة',
    AppText.allergies: 'الحساسية',
    AppText.allergiesSubtitle: 'عدم التحمل',
    AppText.allergiesDesc: 'حساسيتك وعدم تحملك',
    AppText.prevention: 'الوقاية',
    AppText.preventionSubtitle: 'الرعاية الوقائية',
    AppText.preventionDesc: 'الفحوصات الوقائية',
    AppText.bloodPressure: 'ضغط الدم',
    AppText.bloodPressureSubtitle: 'القياسات',
    AppText.bloodPressureDesc: 'ضغط الدم والنبض',
    AppText.weight: 'الوزن',
    AppText.weightSubtitle: 'مؤشر الكتلة والاتجاه',
    AppText.weightDesc: 'متابعة الوزن',
    AppText.healthExport: 'تصدير السجل الصحي',
    AppText.familyCircle: 'دائرة العائلة',
    AppText.interactionCheck: 'التفاعلات',
  },
  AppLanguage.uk: {
    AppText.allAreas: 'ВСІ РОЗДІЛИ',
    AppText.open: 'Відкрити',
    AppText.scanDocument: 'Сканувати документ',
    AppText.dailyPlan: 'Щоденний план',
    AppText.anamnesis: 'Анамнез',
    AppText.anamnesisSubtitle: 'Історія хвороби',
    AppText.anamnesisDesc: 'Ваша медична історія',
    AppText.healthcare: 'Медичні працівники',
    AppText.healthcareSubtitle: 'Лікарі та терапевти',
    AppText.healthcareDesc: 'Усі ваші лікарі та терапевти',
    AppText.treatmentHistory: 'Історія лікування',
    AppText.treatmentHistorySubtitle: 'Огляд лікування',
    AppText.treatmentHistoryDesc: 'Усі процедури з одного погляду',
    AppText.vaccination: 'Сертифікат вакцинації',
    AppText.vaccinationSubtitle: 'Щеплення та паспорти',
    AppText.vaccinationDesc: 'Щеплення та медичні паспорти',
    AppText.medication: 'Ліки',
    AppText.medicationSubtitle: 'План ліків',
    AppText.medicationDesc: 'Ваші поточні ліки',
    AppText.appointments: 'Прийоми',
    AppText.appointmentsSubtitle: 'Медичні прийоми',
    AppText.appointmentsDesc: 'Усі майбутні прийоми',
    AppText.allergies: 'Алергії',
    AppText.allergiesSubtitle: 'Непереносимість',
    AppText.allergiesDesc: 'Ваші алергії та непереносимість',
    AppText.prevention: 'Профілактика',
    AppText.preventionSubtitle: 'Профілактичний догляд',
    AppText.preventionDesc: 'Профілактичні обстеження',
    AppText.bloodPressure: 'Тиск',
    AppText.bloodPressureSubtitle: 'Показники',
    AppText.bloodPressureDesc: 'Тиск і пульс',
    AppText.weight: 'Вага',
    AppText.weightSubtitle: 'BMI і динаміка',
    AppText.weightDesc: 'Контроль ваги',
    AppText.healthExport: 'Експортувати медичну картку',
    AppText.familyCircle: 'Сімейне коло',
    AppText.interactionCheck: 'Взаємодії',
  },
};
